//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenteAutonomo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgenteAutonomo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acessando UDDI ....
        /// </summary>
        internal static string ACESSANDO_UDDI {
            get {
                return ResourceManager.GetString("ACESSANDO_UDDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acessando UDDI para busca do servidor....
        /// </summary>
        internal static string ACESSANDO_UDDI_PARA_BUSCA_DO_SERVIDOR {
            get {
                return ResourceManager.GetString("ACESSANDO_UDDI_PARA_BUSCA_DO_SERVIDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviando URL alternativa. Computador:[{0}].
        /// </summary>
        internal static string ENVIANDO_URL_ALTERNATIVA {
            get {
                return ResourceManager.GetString("ENVIANDO_URL_ALTERNATIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro solicitando reinício Computador:[{0}].
        /// </summary>
        internal static string ERRO_SOLICITANDO_REINICIO {
            get {
                return ResourceManager.GetString("ERRO_SOLICITANDO_REINICIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute como administrador.
        /// </summary>
        internal static string EXECUTE_COMO_ADMIN {
            get {
                return ResourceManager.GetString("EXECUTE_COMO_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recebendo mensagem para Reiniciar Serviço [{0}] no computador [{1}].
        /// </summary>
        internal static string RECEBENDO_MENSAGEM {
            get {
                return ResourceManager.GetString("RECEBENDO_MENSAGEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinicio já foi solicitado e está com erro. Transação deve ser desfeita.
        /// </summary>
        internal static string REINICIO_JA_FOI_SOLICITADO {
            get {
                return ResourceManager.GetString("REINICIO_JA_FOI_SOLICITADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinicio [{0}] solicitado com sucesso.
        /// </summary>
        internal static string REINICIO_SOLICITADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("REINICIO_SOLICITADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisição de Registro Recebida.
        /// </summary>
        internal static string REQUISICAO_REGISTRO_RECEBIDA {
            get {
                return ResourceManager.GetString("REQUISICAO_REGISTRO_RECEBIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço de Resposta iniciado.
        /// </summary>
        internal static string SERVICO_RESPOSTA_AGENTE_INICIADO {
            get {
                return ResourceManager.GetString("SERVICO_RESPOSTA_AGENTE_INICIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço de Solicitação de Ajuda iniciado.
        /// </summary>
        internal static string SERVICO_SOLICITACAO_AJUDA_INICIADO {
            get {
                return ResourceManager.GetString("SERVICO_SOLICITACAO_AJUDA_INICIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servidor encontrado [{0}].
        /// </summary>
        internal static string SERVIDOR_ENCONTRADO {
            get {
                return ResourceManager.GetString("SERVIDOR_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitando reinício do Serviço [{0}] no Computador[{1}].
        /// </summary>
        internal static string SOLICITANDO_REINICIO_SERVIDOR {
            get {
                return ResourceManager.GetString("SOLICITANDO_REINICIO_SERVIDOR", resourceCulture);
            }
        }
    }
}
