//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orquestrador.ServiceReference_SolicitacaoAjuda {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_SolicitacaoAjuda.IService_SolicitacaoAjuda")]
    public interface IService_SolicitacaoAjuda {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_SolicitacaoAjuda/ReiniciaHospedeiro", ReplyAction="http://tempuri.org/IService_SolicitacaoAjuda/ReiniciaHospedeiroResponse")]
        string ReiniciaHospedeiro(string sNomeComputador, string sNomeServico);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService_SolicitacaoAjuda/ReiniciaHospedeiro", ReplyAction="http://tempuri.org/IService_SolicitacaoAjuda/ReiniciaHospedeiroResponse")]
        System.IAsyncResult BeginReiniciaHospedeiro(string sNomeComputador, string sNomeServico, System.AsyncCallback callback, object asyncState);
        
        string EndReiniciaHospedeiro(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_SolicitacaoAjuda/ReiniciaContadores", ReplyAction="http://tempuri.org/IService_SolicitacaoAjuda/ReiniciaContadoresResponse")]
        void ReiniciaContadores();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService_SolicitacaoAjuda/ReiniciaContadores", ReplyAction="http://tempuri.org/IService_SolicitacaoAjuda/ReiniciaContadoresResponse")]
        System.IAsyncResult BeginReiniciaContadores(System.AsyncCallback callback, object asyncState);
        
        void EndReiniciaContadores(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_SolicitacaoAjudaChannel : Orquestrador.ServiceReference_SolicitacaoAjuda.IService_SolicitacaoAjuda, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReiniciaHospedeiroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReiniciaHospedeiroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_SolicitacaoAjudaClient : System.ServiceModel.ClientBase<Orquestrador.ServiceReference_SolicitacaoAjuda.IService_SolicitacaoAjuda>, Orquestrador.ServiceReference_SolicitacaoAjuda.IService_SolicitacaoAjuda {
        
        private BeginOperationDelegate onBeginReiniciaHospedeiroDelegate;
        
        private EndOperationDelegate onEndReiniciaHospedeiroDelegate;
        
        private System.Threading.SendOrPostCallback onReiniciaHospedeiroCompletedDelegate;
        
        private BeginOperationDelegate onBeginReiniciaContadoresDelegate;
        
        private EndOperationDelegate onEndReiniciaContadoresDelegate;
        
        private System.Threading.SendOrPostCallback onReiniciaContadoresCompletedDelegate;
        
        public Service_SolicitacaoAjudaClient() {
        }
        
        public Service_SolicitacaoAjudaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_SolicitacaoAjudaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_SolicitacaoAjudaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_SolicitacaoAjudaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ReiniciaHospedeiroCompletedEventArgs> ReiniciaHospedeiroCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ReiniciaContadoresCompleted;
        
        public string ReiniciaHospedeiro(string sNomeComputador, string sNomeServico) {
            return base.Channel.ReiniciaHospedeiro(sNomeComputador, sNomeServico);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginReiniciaHospedeiro(string sNomeComputador, string sNomeServico, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReiniciaHospedeiro(sNomeComputador, sNomeServico, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndReiniciaHospedeiro(System.IAsyncResult result) {
            return base.Channel.EndReiniciaHospedeiro(result);
        }
        
        private System.IAsyncResult OnBeginReiniciaHospedeiro(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sNomeComputador = ((string)(inValues[0]));
            string sNomeServico = ((string)(inValues[1]));
            return this.BeginReiniciaHospedeiro(sNomeComputador, sNomeServico, callback, asyncState);
        }
        
        private object[] OnEndReiniciaHospedeiro(System.IAsyncResult result) {
            string retVal = this.EndReiniciaHospedeiro(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReiniciaHospedeiroCompleted(object state) {
            if ((this.ReiniciaHospedeiroCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReiniciaHospedeiroCompleted(this, new ReiniciaHospedeiroCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReiniciaHospedeiroAsync(string sNomeComputador, string sNomeServico) {
            this.ReiniciaHospedeiroAsync(sNomeComputador, sNomeServico, null);
        }
        
        public void ReiniciaHospedeiroAsync(string sNomeComputador, string sNomeServico, object userState) {
            if ((this.onBeginReiniciaHospedeiroDelegate == null)) {
                this.onBeginReiniciaHospedeiroDelegate = new BeginOperationDelegate(this.OnBeginReiniciaHospedeiro);
            }
            if ((this.onEndReiniciaHospedeiroDelegate == null)) {
                this.onEndReiniciaHospedeiroDelegate = new EndOperationDelegate(this.OnEndReiniciaHospedeiro);
            }
            if ((this.onReiniciaHospedeiroCompletedDelegate == null)) {
                this.onReiniciaHospedeiroCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReiniciaHospedeiroCompleted);
            }
            base.InvokeAsync(this.onBeginReiniciaHospedeiroDelegate, new object[] {
                        sNomeComputador,
                        sNomeServico}, this.onEndReiniciaHospedeiroDelegate, this.onReiniciaHospedeiroCompletedDelegate, userState);
        }
        
        public void ReiniciaContadores() {
            base.Channel.ReiniciaContadores();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginReiniciaContadores(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReiniciaContadores(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndReiniciaContadores(System.IAsyncResult result) {
            base.Channel.EndReiniciaContadores(result);
        }
        
        private System.IAsyncResult OnBeginReiniciaContadores(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginReiniciaContadores(callback, asyncState);
        }
        
        private object[] OnEndReiniciaContadores(System.IAsyncResult result) {
            this.EndReiniciaContadores(result);
            return null;
        }
        
        private void OnReiniciaContadoresCompleted(object state) {
            if ((this.ReiniciaContadoresCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReiniciaContadoresCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReiniciaContadoresAsync() {
            this.ReiniciaContadoresAsync(null);
        }
        
        public void ReiniciaContadoresAsync(object userState) {
            if ((this.onBeginReiniciaContadoresDelegate == null)) {
                this.onBeginReiniciaContadoresDelegate = new BeginOperationDelegate(this.OnBeginReiniciaContadores);
            }
            if ((this.onEndReiniciaContadoresDelegate == null)) {
                this.onEndReiniciaContadoresDelegate = new EndOperationDelegate(this.OnEndReiniciaContadores);
            }
            if ((this.onReiniciaContadoresCompletedDelegate == null)) {
                this.onReiniciaContadoresCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReiniciaContadoresCompleted);
            }
            base.InvokeAsync(this.onBeginReiniciaContadoresDelegate, null, this.onEndReiniciaContadoresDelegate, this.onReiniciaContadoresCompletedDelegate, userState);
        }
    }
}
