//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenteMonitorRecurso.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgenteMonitorRecurso.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre com o nome do computador.
        /// </summary>
        internal static string ENTRE_COM_NOME_COMPUTADOR {
            get {
                return ResourceManager.GetString("ENTRE_COM_NOME_COMPUTADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre com o nome do serviço.
        /// </summary>
        internal static string ENTRE_COM_NOME_DO_SERVICO {
            get {
                return ResourceManager.GetString("ENTRE_COM_NOME_DO_SERVICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute como administrador.
        /// </summary>
        internal static string EXECUTE_COMO_ADMIN {
            get {
                return ResourceManager.GetString("EXECUTE_COMO_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando serviço.
        /// </summary>
        internal static string INICIANDO_SERVIDOR {
            get {
                return ResourceManager.GetString("INICIANDO_SERVIDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parando serviço.
        /// </summary>
        internal static string PARANDO_SERVIDOR {
            get {
                return ResourceManager.GetString("PARANDO_SERVIDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reativando Serviço.
        /// </summary>
        internal static string REATIVANDO_SERVICO {
            get {
                return ResourceManager.GetString("REATIVANDO_SERVICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recebendo mensagem para reiniciar Serviço [{0}] no computador [{1}].
        /// </summary>
        internal static string RECEBENDO_MENSAGEM {
            get {
                return ResourceManager.GetString("RECEBENDO_MENSAGEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço Gerenciador de Recurso iniciado.
        /// </summary>
        internal static string SERVICO_GERENCIADOR_RECURSO_INICIADO {
            get {
                return ResourceManager.GetString("SERVICO_GERENCIADOR_RECURSO_INICIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço já se encontra parado.
        /// </summary>
        internal static string SERVICO_JA_PARADO {
            get {
                return ResourceManager.GetString("SERVICO_JA_PARADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servidor [{0}] reiniciado.
        /// </summary>
        internal static string SERVIDOR_REINICIADO {
            get {
                return ResourceManager.GetString("SERVIDOR_REINICIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso negado.Tente executar o programa como Administrador. Verifique o nome do computador e o nome do serviço.
        /// </summary>
        internal static string TENTE_EXECUTAR_COMO_ADMINISTRADOR {
            get {
                return ResourceManager.GetString("TENTE_EXECUTAR_COMO_ADMINISTRADOR", resourceCulture);
            }
        }
    }
}
