//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenteAutonomo.ServiceReference_AgenteMonitorRecurso {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_AgenteMonitorRecurso.IService_Gerenciador_Recurso")]
    public interface IService_Gerenciador_Recurso {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Gerenciador_Recurso/ReiniciaServico", ReplyAction="http://tempuri.org/IService_Gerenciador_Recurso/ReiniciaServicoResponse")]
        string ReiniciaServico(string sNomeServico, string sNomeMaquina, int iTimeoutMilliseconds);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService_Gerenciador_Recurso/ReiniciaServico", ReplyAction="http://tempuri.org/IService_Gerenciador_Recurso/ReiniciaServicoResponse")]
        System.IAsyncResult BeginReiniciaServico(string sNomeServico, string sNomeMaquina, int iTimeoutMilliseconds, System.AsyncCallback callback, object asyncState);
        
        string EndReiniciaServico(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_Gerenciador_RecursoChannel : AgenteAutonomo.ServiceReference_AgenteMonitorRecurso.IService_Gerenciador_Recurso, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReiniciaServicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReiniciaServicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_Gerenciador_RecursoClient : System.ServiceModel.ClientBase<AgenteAutonomo.ServiceReference_AgenteMonitorRecurso.IService_Gerenciador_Recurso>, AgenteAutonomo.ServiceReference_AgenteMonitorRecurso.IService_Gerenciador_Recurso {
        
        private BeginOperationDelegate onBeginReiniciaServicoDelegate;
        
        private EndOperationDelegate onEndReiniciaServicoDelegate;
        
        private System.Threading.SendOrPostCallback onReiniciaServicoCompletedDelegate;
        
        public Service_Gerenciador_RecursoClient() {
        }
        
        public Service_Gerenciador_RecursoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_Gerenciador_RecursoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_Gerenciador_RecursoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_Gerenciador_RecursoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ReiniciaServicoCompletedEventArgs> ReiniciaServicoCompleted;
        
        public string ReiniciaServico(string sNomeServico, string sNomeMaquina, int iTimeoutMilliseconds) {
            return base.Channel.ReiniciaServico(sNomeServico, sNomeMaquina, iTimeoutMilliseconds);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginReiniciaServico(string sNomeServico, string sNomeMaquina, int iTimeoutMilliseconds, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReiniciaServico(sNomeServico, sNomeMaquina, iTimeoutMilliseconds, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndReiniciaServico(System.IAsyncResult result) {
            return base.Channel.EndReiniciaServico(result);
        }
        
        private System.IAsyncResult OnBeginReiniciaServico(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sNomeServico = ((string)(inValues[0]));
            string sNomeMaquina = ((string)(inValues[1]));
            int iTimeoutMilliseconds = ((int)(inValues[2]));
            return this.BeginReiniciaServico(sNomeServico, sNomeMaquina, iTimeoutMilliseconds, callback, asyncState);
        }
        
        private object[] OnEndReiniciaServico(System.IAsyncResult result) {
            string retVal = this.EndReiniciaServico(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReiniciaServicoCompleted(object state) {
            if ((this.ReiniciaServicoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReiniciaServicoCompleted(this, new ReiniciaServicoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReiniciaServicoAsync(string sNomeServico, string sNomeMaquina, int iTimeoutMilliseconds) {
            this.ReiniciaServicoAsync(sNomeServico, sNomeMaquina, iTimeoutMilliseconds, null);
        }
        
        public void ReiniciaServicoAsync(string sNomeServico, string sNomeMaquina, int iTimeoutMilliseconds, object userState) {
            if ((this.onBeginReiniciaServicoDelegate == null)) {
                this.onBeginReiniciaServicoDelegate = new BeginOperationDelegate(this.OnBeginReiniciaServico);
            }
            if ((this.onEndReiniciaServicoDelegate == null)) {
                this.onEndReiniciaServicoDelegate = new EndOperationDelegate(this.OnEndReiniciaServico);
            }
            if ((this.onReiniciaServicoCompletedDelegate == null)) {
                this.onReiniciaServicoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReiniciaServicoCompleted);
            }
            base.InvokeAsync(this.onBeginReiniciaServicoDelegate, new object[] {
                        sNomeServico,
                        sNomeMaquina,
                        iTimeoutMilliseconds}, this.onEndReiniciaServicoDelegate, this.onReiniciaServicoCompletedDelegate, userState);
        }
    }
}
