//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orquestrador.ServiceReference_RespostaAgente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_RespostaAgente.IService_RespostaAgente", CallbackContract=typeof(Orquestrador.ServiceReference_RespostaAgente.IService_RespostaAgenteCallback))]
    public interface IService_RespostaAgente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_RespostaAgente/IniciaEscuta", ReplyAction="http://tempuri.org/IService_RespostaAgente/IniciaEscutaResponse")]
        string IniciaEscuta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_RespostaAgente/IniciaEscuta", ReplyAction="http://tempuri.org/IService_RespostaAgente/IniciaEscutaResponse")]
        System.Threading.Tasks.Task<string> IniciaEscutaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_RespostaAgenteCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_RespostaAgente/Responde", ReplyAction="http://tempuri.org/IService_RespostaAgente/RespondeResponse")]
        void Responde(string sMensagem, bool bErro, string sServidorAlternativo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_RespostaAgenteChannel : Orquestrador.ServiceReference_RespostaAgente.IService_RespostaAgente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_RespostaAgenteClient : System.ServiceModel.DuplexClientBase<Orquestrador.ServiceReference_RespostaAgente.IService_RespostaAgente>, Orquestrador.ServiceReference_RespostaAgente.IService_RespostaAgente {
        
        public Service_RespostaAgenteClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public Service_RespostaAgenteClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public Service_RespostaAgenteClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service_RespostaAgenteClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service_RespostaAgenteClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string IniciaEscuta() {
            return base.Channel.IniciaEscuta();
        }
        
        public System.Threading.Tasks.Task<string> IniciaEscutaAsync() {
            return base.Channel.IniciaEscutaAsync();
        }
    }
}
