//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orquestrador.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orquestrador.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acessando servidor alternativo [{0}].
        /// </summary>
        internal static string ACESSANDO_SERVIDOR_ALTERNATIVO {
            get {
                return ResourceManager.GetString("ACESSANDO_SERVIDOR_ALTERNATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desfazendo Transação.
        /// </summary>
        internal static string DESFAZENDO_TRANSACAO {
            get {
                return ResourceManager.GetString("DESFAZENDO_TRANSACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro:HResult:[{0}]\n&lt;Descrição:[{1}].
        /// </summary>
        internal static string ERRO_HRESULT {
            get {
                return ResourceManager.GetString("ERRO_HRESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro obtendo servidor.
        /// </summary>
        internal static string ERRO_OBTENDO_SERVIDOR {
            get {
                return ResourceManager.GetString("ERRO_OBTENDO_SERVIDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}:8733/Service_Monitorado/Service_Monitorado/.
        /// </summary>
        internal static string NOME_SERVICO_MONITORADO {
            get {
                return ResourceManager.GetString("NOME_SERVICO_MONITORADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo:[{0}] computador:[{1}] função: [{2}].
        /// </summary>
        internal static string PROCESSO {
            get {
                return ResourceManager.GetString("PROCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo:[{0}] computador:[{1}] função: [{2}] resultado:[{3}].
        /// </summary>
        internal static string PROCESSO_RESULTADO {
            get {
                return ResourceManager.GetString("PROCESSO_RESULTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recebendo URL e máquina alternativa. Computador:[{0}].
        /// </summary>
        internal static string RECEBENDO_URL_ALTERNATIVA {
            get {
                return ResourceManager.GetString("RECEBENDO_URL_ALTERNATIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinicio já foi solicitado e está com erro. Transação deve ser desfeita.
        /// </summary>
        internal static string REINICIO_JA_SOLICITADO_TRANSACAO_DEVE_SER_DESFEITA {
            get {
                return ResourceManager.GetString("REINICIO_JA_SOLICITADO_TRANSACAO_DEVE_SER_DESFEITA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB({0},{1},{2}).
        /// </summary>
        internal static string RGB {
            get {
                return ResourceManager.GetString("RGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servidor encontrado [{0}].
        /// </summary>
        internal static string SERVIDOR_INICIAL {
            get {
                return ResourceManager.GetString("SERVIDOR_INICIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação de Registro.
        /// </summary>
        internal static string SOLICITACAO_ESCUTA {
            get {
                return ResourceManager.GetString("SOLICITACAO_ESCUTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitando reinício serviço [{0}] no computador [{1}].
        /// </summary>
        internal static string SOLICITACAO_REINICIO {
            get {
                return ResourceManager.GetString("SOLICITACAO_REINICIO", resourceCulture);
            }
        }
    }
}
